apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jupyterlab-read-only-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: jupyterlab
roleRef:
  kind: ClusterRole
  name: jupyterlab-read-only-role
  apiGroup: rbac.authorization.k8s.io

