apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: airflow
data:
  airflow.cfg: |
    [core]
    sql_alchemy_conn = postgresql+psycopg2://airflow:Itversity123@airflow-postgresql:5432/airflow
    executor = LocalExecutor
    load_examples = False

    [logging]
    base_log_folder = /opt/airflow/logs
    remote_logging = True

    [webserver]
    base_url = http://localhost:8080
    web_server_host = 0.0.0.0
    web_server_port = 8080