apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-config
  namespace: spark-updated
data:
  spark-defaults.conf: |
    spark.executor.instances=2
    spark.executor.memory=2g
    spark.driver.memory=1g
    spark.master=spark://spark-master:7077
    spark.eventLog.enabled=true
    spark.eventLog.dir=/tmp/spark-events
    spark.history.fs.logDirectory=/tmp/spark-events
    spark.ui.proxyBase=/spark
