apiVersion: batch/v1
kind: Job
metadata:
  name: spark-metastore-init
  namespace: spark
spec:
  template:
    spec:
      containers:
      - name: spark-metastore-init
        image: dgadiraju/itvhive:3.1.3
        command: ["sh", "-c", "schematool -dbType postgres -initSchema --verbose"]
        env:
        - name: HIVE_METASTORE_DB_TYPE
          value: "postgres"
        - name: HIVE_METASTORE_DB_HOST
          value: "spark-postgresql"
        - name: HIVE_METASTORE_DB_PORT
          value: "5432"
        - name: HIVE_METASTORE_DB_NAME
          value: "spark"
        - name: HIVE_METASTORE_DB_USER
          value: "spark"
        - name: HIVE_METASTORE_DB_PASS
          valueFrom:
            secretKeyRef:
              name: spark-postgresql
              key: spark-postgres-password
        volumeMounts:
        - name: hive-config
          mountPath: /opt/hive/conf
      restartPolicy: OnFailure
      volumes:
      - name: hive-config
        configMap:
          name: hive-config