apiVersion: v1
kind: Service
metadata:
  name: spark-postgresql
  namespace: spark
spec:
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30007
  selector:
    app: spark-postgresql
  type: NodePort