apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-postgres-config
  namespace: spark
data:
  postgresql.conf: |
    # -----------------------------
    # PostgreSQL configuration file
    # -----------------------------

    #------------------------------------------------------------------------------
    # FILE LOCATIONS
    #------------------------------------------------------------------------------

    #------------------------------------------------------------------------------
    # CONNECTIONS AND AUTHENTICATION
    #------------------------------------------------------------------------------
    listen_addresses = '*'
    max_connections = 100
    password_encryption = md5

    #------------------------------------------------------------------------------
    # RESOURCE USAGE (except WAL)
    #------------------------------------------------------------------------------
    dynamic_shared_memory_type = posix 

    #------------------------------------------------------------------------------
    # WRITE-AHEAD LOG
    #------------------------------------------------------------------------------
    max_wal_size = 1GB
    min_wal_size = 80MB

    #------------------------------------------------------------------------------
    # REPLICATION
    #------------------------------------------------------------------------------

    #------------------------------------------------------------------------------
    # QUERY TUNING
    #------------------------------------------------------------------------------

    #------------------------------------------------------------------------------
    # REPORTING AND LOGGING
    #------------------------------------------------------------------------------
    log_timezone = 'Etc/UTC'

    #------------------------------------------------------------------------------
    # PROCESS TITLE
    #------------------------------------------------------------------------------

    #------------------------------------------------------------------------------
    # STATISTICS
    #------------------------------------------------------------------------------

    #------------------------------------------------------------------------------
    # AUTOVACUUM
    #------------------------------------------------------------------------------

    #------------------------------------------------------------------------------
    # CLIENT CONNECTION DEFAULTS
    #------------------------------------------------------------------------------
    # These settings are initialized by initdb, but they can be changed.
    lc_messages = 'en_US.utf8'                      # locale for system error message
                                            # strings
    lc_monetary = 'en_US.utf8'                      # locale for monetary formatting
    lc_numeric = 'en_US.utf8'                       # locale for number formatting
    lc_time = 'en_US.utf8'                          # locale for time formatting

    #------------------------------------------------------------------------------
    # LOCK MANAGEMENT
    #------------------------------------------------------------------------------

    #------------------------------------------------------------------------------
    # VERSION AND PLATFORM COMPATIBILITY
    #------------------------------------------------------------------------------

    #------------------------------------------------------------------------------
    # ERROR HANDLING
    #------------------------------------------------------------------------------

    #------------------------------------------------------------------------------
    # CONFIG FILE INCLUDES
    #------------------------------------------------------------------------------

    #------------------------------------------------------------------------------
    # CUSTOMIZED OPTIONS
    #------------------------------------------------------------------------------

    # Add settings for extensions here
  pg_hba.conf: |
    # PostgreSQL Client Authentication Configuration File
    # TYPE  DATABASE        USER            ADDRESS                 METHOD

    # "local" is for Unix domain socket connections only
    local   all             all                                     md5
    # IPv4 local connections:
    host    all             all             0.0.0.0/0               md5
    # IPv6 local connections:
    host    all             all             ::/0                    md5
    # Allow replication connections from localhost, by a user with the
    # replication privilege.
    local   replication     all                                     md5
    host    replication     all             0.0.0.0/0               md5
    host    replication     all             ::/0                    md5
