apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: python
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # Change this to the actual port your Python app listens on
