---
- name: Disabling Swap on all nodes
  shell: swapoff -a

- name: Commenting Swap entries in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^(.*swap.*)$'
    replace: '#\1'

- name: Remove existing Kubernetes apt repository key if it exists
  shell: sudo rm -f /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  ignore_errors: true

- name: Add Kubernetes apt repository key
  shell: |
    sudo mkdir -p /etc/apt/keyrings
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes apt repository
  shell: |
    echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

- name: Update apt package cache
  apt:
    update_cache: yes

- name: Installing required packages for Kubernetes
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - kubeadm
    - kubelet
    - kubectl

- name: Configure kubelet cgroup driver
  copy:
    dest: /etc/default/kubelet
    content: |
      KUBELET_EXTRA_ARGS=--cgroup-driver=systemd

- name: Restart and enable kubelet
  service:
    name: kubelet
    state: restarted
    enabled: yes
