apiVersion: v1
kind: PersistentVolume
metadata:
  name: superset-static-pv
  namespace: superset1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/superset/static  # Update this path based on your setup
