apiVersion: v1
kind: Service
metadata:
  name: superset1-service
  namespace: superset1
spec:
  selector:
    app: superset1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8088
  type: NodePort
