apiVersion: v1
kind: Secret
metadata:
  name: superset-secrets
  namespace: superset
type: Opaque
data:
  superset-secret-key: eDdrVnVpUTF5blRDT2F5MGJRdFZqYVcxYXA3bmhDUTRzVjBISStLcjdDQmxQd3FqM2hxWlEvZlMK