apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyterlab-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  # Ensure this matches your PVC's storageClassName
  hostPath:
    path: /mnt/data/jupyterlab
