---
- name: Remove existing kubelet.conf if it exists
  file:
    path: /etc/kubernetes/kubelet.conf
    state: absent

- name: Remove existing ca.crt if it exists
  file:
    path: /etc/kubernetes/pki/ca.crt
    state: absent

- name: Ensure containerd is restarted and enabled
  service:
    name: containerd
    state: restarted
    enabled: yes

# - name: Retrieve join token from master node if it exists
#   fetch:
#     src: /tmp/kubeadm_init_output/join_token.txt
#     dest: /tmp/join_token.txt
#     flat: yes
#   delegate_to: "{{ groups['kubernetes-master-node'][0] }}"
#   register: join_token_fetch_result

# - name: Join worker node to the cluster
#   command: "{{ lookup('file', '/tmp/join_token.txt') }} --ignore-preflight-errors=FileAvailable--etc-kubernetes-kubelet.conf,FileAvailable--etc-kubernetes-pki-ca.crt,CRI --v=5"
#   when: join_token_fetch_result is succeeded
