apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  namespace: minio-operators
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv-claim
  namespace: minio-operators
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
