apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: metallb-system
  name: metallb-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metallb-system
subjects:
  - kind: ServiceAccount
    name: speaker
    namespace: metallb-system
  - kind: ServiceAccount
    name: controller
    namespace: metallb-system


