apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: airflow
spec:
  containers:
    - name: test-container
      image: busybox
      command: ["sh", "-c", "echo Hello OpenEBS > /mnt/testfile && sleep 3600"]
      volumeMounts:
        - name: test-volume
          mountPath: /mnt
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: test-pvc