apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: airflow
spec:
  storageClassName: openebs-hostpath  # change this to your OpenEBS storage class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi