apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-service-account
  namespace: spark-updated

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: spark-updated
  name: spark-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["create", "get", "list", "watch", "delete"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: spark-updated
subjects:
- kind: ServiceAccount
  name: spark-service-account
  namespace: spark-updated
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io

