apiVersion: v1
kind: Pod
metadata:
  name: spark-driver
  namespace: spark
spec:
  containers:
  - name: spark-driver
    image: bitnami/spark:latest
    env:
    - name: MINIO_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: minio-credentials
          key: accesskey
    - name: MINIO_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: minio-credentials
          key: secretkey
    command: ["/bin/bash", "-c", "sleep infinity"]
